name: Keep Codespace Alive

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Keep Codespace Alive
        run: echo "Keeping Codespace Alive"
